-- Migration: Create ENUM types
-- Purpose: Define custom enum types for flashcard sources and generation statuses
-- Created: 2025-10-26
-- Tables affected: Will be used by flashcards and generations tables
--
-- Note: These enums should be created before the tables that reference them

-- create enum type for flashcard source
-- values indicate how the flashcard was created:
--   - 'ai_full': completely generated by AI without edits
--   - 'ai_edited': generated by AI but edited by user
--   - 'manual': manually created by user
create type flashcard_source as enum ('ai_full', 'ai_edited', 'manual');

-- create enum type for generation status
-- values indicate the current state of a generation request:
--   - 'pending': generation is in progress
--   - 'completed': generation finished successfully
--   - 'failed': generation encountered an error
create type generation_status as enum ('pending', 'completed', 'failed');

